import type { QueryResultRow } from 'pg';
import type { ActionAttempt, AttemptHttpClass, OrderAction, OrderActionKind } from '../../types';

export type ActionRow = QueryResultRow & Record<string, unknown>;

export const iso = (value: unknown): string => (
    value instanceof Date ? value : new Date(String(value))
).toISOString();

export const optional = (value: unknown): string | undefined => (
    value === null || value === undefined ? undefined : String(value)
);

export const mapAction = (row: ActionRow): OrderAction => {
    const leaseOwner = optional(row.lease_owner);
    return {
        id: String(row.id),
        orderId: String(row.order_id),
        userId: String(row.user_id),
        legId: optional(row.leg_id),
        parentId: optional(row.parent_action),
        kind: row.kind as OrderActionKind,
        ruleVer: Number(row.rule_ver) as 1,
        clientKey: String(row.client_key),
        reqHash: String(row.req_hash),
        desiredHash: String(row.desired_hash),
        expectedVer: String(row.expected_ver),
        version: String(row.action_ver),
        workState: row.work_state as OrderAction['workState'],
        effectState: row.effect_state as OrderAction['effectState'],
        outcome: row.outcome as OrderAction['outcome'],
        blockReason: optional(row.block_reason) as OrderAction['blockReason'],
        provider: String(row.provider),
        providerReqId: optional(row.provider_req_id),
        providerOrderId: optional(row.provider_order_id),
        firstSignature: optional(row.first_signature),
        messageHash: optional(row.message_hash),
        recentBlockhash: optional(row.recent_blockhash),
        lastValidHeight: optional(row.last_valid_height),
        attemptCount: Number(row.attempt_count),
        dueAt: iso(row.due_at),
        lease: leaseOwner ? {
            owner: leaseOwner,
            gen: String(row.lease_gen),
            scope: String(row.write_scope),
            epoch: String(row.write_epoch),
            until: iso(row.lease_until),
        } : undefined,
        ambiguityAt: row.ambiguity_at ? iso(row.ambiguity_at) : undefined,
        providerCheckAt: row.provider_check_at ? iso(row.provider_check_at) : undefined,
        chainCheckAt: row.chain_check_at ? iso(row.chain_check_at) : undefined,
        errorCode: optional(row.error_code),
        errorClass: optional(row.error_class),
        errorMessage: optional(row.error_message),
        httpClass: optional(row.http_class),
        retryAfter: row.retry_after ? iso(row.retry_after) : undefined,
        completedAt: row.completed_at ? iso(row.completed_at) : undefined,
        createdAt: iso(row.created_at),
        updatedAt: iso(row.updated_at),
    };
};

export const mapAttempt = (row: ActionRow): ActionAttempt => ({
    id: String(row.id),
    actionId: String(row.action_id),
    seq: Number(row.seq),
    leaseGen: String(row.lease_gen),
    writeScope: String(row.write_scope),
    writeEpoch: String(row.write_epoch),
    endpoint: String(row.endpoint),
    method: row.method as ActionAttempt['method'],
    provider: String(row.provider),
    reqHash: String(row.req_hash),
    bodyHash: optional(row.body_hash),
    desiredHash: String(row.desired_hash),
    providerReqId: optional(row.provider_req_id),
    blobActionId: optional(row.blob_action_id),
    sendState: row.send_state as ActionAttempt['sendState'],
    startedAt: row.started_at ? iso(row.started_at) : undefined,
    deadlineAt: iso(row.deadline_at),
    completedAt: row.completed_at ? iso(row.completed_at) : undefined,
    httpStatus: row.http_status === null || row.http_status === undefined
        ? undefined : Number(row.http_status),
    httpClass: optional(row.http_class) as AttemptHttpClass | undefined,
    responseHash: optional(row.response_hash),
    providerEffectId: optional(row.provider_effect_id),
    errorCode: optional(row.error_code),
    errorMessage: optional(row.error_message),
    createdAt: iso(row.created_at),
});

export const actionFact = (action: OrderAction): Record<string, unknown> => ({
    id: action.id,
    orderId: action.orderId,
    userId: action.userId,
    legId: action.legId ?? null,
    parentId: action.parentId ?? null,
    kind: action.kind,
    ruleVer: action.ruleVer,
    clientKey: action.clientKey,
    reqHash: action.reqHash,
    desiredHash: action.desiredHash,
    expectedVer: action.expectedVer,
    version: action.version,
    workState: action.workState,
    effectState: action.effectState,
    outcome: action.outcome,
    blockReason: action.blockReason ?? null,
    provider: action.provider,
    providerReqId: action.providerReqId ?? null,
    providerOrderId: action.providerOrderId ?? null,
    firstSignature: action.firstSignature ?? null,
    messageHash: action.messageHash ?? null,
    recentBlockhash: action.recentBlockhash ?? null,
    lastValidHeight: action.lastValidHeight ?? null,
    attemptCount: action.attemptCount,
    dueAt: action.dueAt,
    lease: action.lease ? {
        owner: action.lease.owner,
        gen: action.lease.gen,
        scope: action.lease.scope,
        epoch: action.lease.epoch,
        until: action.lease.until,
    } : null,
    ambiguityAt: action.ambiguityAt ?? null,
    providerCheckAt: action.providerCheckAt ?? null,
    chainCheckAt: action.chainCheckAt ?? null,
    errorCode: action.errorCode ?? null,
    errorClass: action.errorClass ?? null,
    errorMessage: action.errorMessage ?? null,
    httpClass: action.httpClass ?? null,
    retryAfter: action.retryAfter ?? null,
    completedAt: action.completedAt ?? null,
    createdAt: action.createdAt,
    updatedAt: action.updatedAt,
});

export const attemptFact = (attempt: ActionAttempt): Record<string, unknown> => ({
    id: attempt.id,
    actionId: attempt.actionId,
    seq: attempt.seq,
    leaseGen: attempt.leaseGen,
    writeScope: attempt.writeScope,
    writeEpoch: attempt.writeEpoch,
    endpoint: attempt.endpoint,
    method: attempt.method,
    provider: attempt.provider,
    reqHash: attempt.reqHash,
    bodyHash: attempt.bodyHash ?? null,
    desiredHash: attempt.desiredHash,
    providerReqId: attempt.providerReqId ?? null,
    blobActionId: attempt.blobActionId ?? null,
    sendState: attempt.sendState,
    startedAt: attempt.startedAt ?? null,
    deadlineAt: attempt.deadlineAt,
    completedAt: attempt.completedAt ?? null,
    httpStatus: attempt.httpStatus ?? null,
    httpClass: attempt.httpClass ?? null,
    responseHash: attempt.responseHash ?? null,
    providerEffectId: attempt.providerEffectId ?? null,
    errorCode: attempt.errorCode ?? null,
    errorMessage: attempt.errorMessage ?? null,
    createdAt: attempt.createdAt,
});
